---
title: '{== redoc ==}{>> Good work! (alanye01) <<}'
subtitle: Demo
author: Alan Yeung
date: 01 January 2001
output:
  redoc::rdocx_reversible:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

R Markdown
----------

This is an {-- R Markdown --}{++ redoc ++} document. Markdown is a simple
formatting syntax for authoring HTML, PDF, and MS Word documents. For more
details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes
both content as well as the output of any embedded R code chunks within the
document. You can embed an R code chunk like this:

```{r cars}
summary(cars)
```

Including Plots
---------------

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

{++ Figure 1 Need a caption ++}

Note that the `echo = FALSE` parameter was added to the code chunk to prevent
printing of the R code that generated the plot.

{-- 1 --}{++ 2 ++}[]{.paragraph-insertion author="alanye01"
date="2019-03-04T21:49:00Z"}

{++ Trying the kable() function would be useful as well. ++}
